name: ivo_service_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+6

environment:
  sdk: ^3.10.1

dependencies:
  device_info_plus: ^12.3.0
  get: ^4.7.3
  dio: ^5.9.0
  flutter:
    sdk: flutter
  google_fonts: ^6.3.3
  package_info_plus: ^9.0.0
  permission_handler: ^12.0.1
  shared_preferences: ^2.5.3
  firebase_core: ^4.3.0
  firebase_messaging: ^16.1.0
  url_launcher: ^6.3.2
  flutter_linkify: ^6.0.0
  app_badge_plus: ^1.2.6
  flutter_spinkit: ^5.2.2
  snow_fall_animation: ^0.0.1+3
  app_links: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/on_boarding_images/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/app_logo.png"
  adaptive_icon_background: "#FFFFFF" 
  adaptive_icon_foreground: "assets/icons/app_logo.png"
